spring:
  application:
    name: service-hi
  profiles:
    active: peer1
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:9001/eureka/,http://peer2:9002/eureka/,http://peer3:9003/eureka/