spring:
  application:
    name: service-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:9001/eureka/,http://peer2:9002/eureka/,http://peer3:9003/eureka/
feign:
  hystrix:
    enabled: true

hystrix:
  metrics:
    enabled: true
  command:
    ##全局方法使用default
    SchedualServiceHi#sayHiFromClientOne():
      execution:
        isolation:
          thread:
            ##超时时间
            timeoutInMilliseconds: 5000
      circuitBreaker:
        ##每秒3次请求
        requestVolumeThreshold: 3

